spring.application.name=servicio-pagos

server.port=8086
spring.datasource.url=jdbc:mysql://mysql-server:3306/gb_pagos
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=pagos-group-v2
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=e41697ee-1b10-4b64-95da-b32ec0fdb9a7
spring.cloud.azure.active-directory.credential.client-id=7f32a189-8be6-4f14-92ab-9d8e80fac2bc
spring.cloud.azure.active-directory.app-id-uri=api://7f32a189-8be6-4f14-92ab-9d8e80fac2bc