spring.application.name=servicio-usuarios

server.port=8080

spring.datasource.url=jdbc:mysql://mysql-server:3306/gb_usuarios
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=e41697ee-1b10-4b64-95da-b32ec0fdb9a7
spring.cloud.azure.active-directory.credential.client-id=7f32a189-8be6-4f14-92ab-9d8e80fac2bc
spring.cloud.azure.active-directory.app-id-uri=api://7f32a189-8be6-4f14-92ab-9d8e80fac2bc

# Configuración OAuth2 Resource Server para Microsoft Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/e41697ee-1b10-4b64-95da-b32ec0fdb9a7/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/e41697ee-1b10-4b64-95da-b32ec0fdb9a7/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audience=api://7f32a189-8be6-4f14-92ab-9d8e80fac2bc